### ISSUE TITLE
Refactorings

### ISSUE THREAD

**Issue by dtlhlbs** [hilltop-software/sampler_qa_checks_demo#2]
Checks have dependencies on Hilltop and HilltopHost that could be injected/abstracted to make checks testable.

OutsideRangeCheck can use the tuple config instead of min/max, e.g. 

```yaml
OutsideRangeCheck:
  "pH": # Hilltop measurement name
    critical: 
      min: 5
      max: 9
    warning:
      min: 6
      max: 8
```

to

```yaml
OutsideRangeCheck:
  "pH": # Hilltop measurement name
    critical: 5,9
    warning: 6,8
```

This also allows us to move PercentileCheck.validate_range to ICheck for re-use. OutsideRangeCheck should be more like PercentileCheck when retrieving, validating and checking ranges.
